### ISSUE TITLE
计划找个时间组织一次HIT(or Harbin) Github User Drinkup

### ISSUE THREAD

**Issue by cliffwoo** [HIT-ON-Github/About#3]
可以在一起交流一下，不知道大家都有兴趣没？

**Comment by hit9** [comment]
:+1:

**Comment by countcain** [comment]
有意思
在 2013-4-19 下午3:30，"Wu Jin" notifications@github.com写道：

**Comment by guori12321** [comment]
仰慕Cliff很久了 什么时候去围观下~

2013/4/19 Huang Tao (￣ε ￣ notifications@github.com

> 有意思
> 在 2013-4-19 下午3:30，"Wu Jin" notifications@github.com写道：
> 
> > 可以在一起交流一下，不知道大家都有兴趣没？
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HIT-ON-Github/About/issues/3>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HIT-ON-Github/About/issues/3#issuecomment-16639807
> .

## 

```
祝好！
```

哈尔滨工业大学 软件学院 10级本科 郭锐

**Comment by cliffwoo** [comment]
随时欢迎来新技术楼

**Comment by hit9** [comment]
需要定时间嘛？

在 2013-04-19 15:30:58，"Wu Jin" notifications@github.com 写道：

可以在一起交流一下，不知道大家都有兴趣没？

**Comment by cliffwoo** [comment]
等我组织一下，再和大家确认
在 2013-4-19 下午4:51，"Wang Chao" notifications@github.com写道：

**Comment by void-main** [comment]
教练～～我也想去！～

**Comment by hit9** [comment]
ok ~

在 2013-04-19 16:52:49，"Wu Jin" notifications@github.com 写道：
等我组织一下，再和大家确认
在 2013-4-19 下午4:51，"Wang Chao" notifications@github.com写道：

**Comment by cliffwoo** [comment]
@void-main 你可以考虑5.1先回哈尔滨

**Comment by void-main** [comment]
@cliffwoo 求贵组织提供往返站票！～哈哈～～

**Comment by cliffwoo** [comment]
@void-main 往返跪票必须提供

**Comment by void-main** [comment]
@cliffwoo 眼泪掉下来～～就是这么迎接基佬的么～～

**Comment by tonyzhu** [comment]
@void-main 靠。。你不就想回去啪啪啪么

**Comment by void-main** [comment]
@tonyzhu 我是去参加基佬聚会的～～谢谢！～
