### ISSUE TITLE
Drinkup 日期

### ISSUE THREAD

**Issue by cliffwoo** [HIT-ON-Github/About#6]
计划定在  28 ，29 两天
大家都说说哪天有空，尽量统一一下时间

**Comment by void-main** [comment]
29号＋1，另外跪求Hackathon！

**Comment by cliffwoo** [comment]
@void-main Hackathon，您的体力成吗？

**Comment by void-main** [comment]
@cliffwoo 完全没问题！～可以3P开发嘛～～一个倒下了还有两个～～哈哈～～

**Comment by hit9** [comment]
你们五一不出去玩么！~ 早两天吧

在 2013-04-20 10:34:39，"Wu Jin" notifications@github.com 写道：

@void-main Hackathon，您的体力成吗？

**Comment by cliffwoo** [comment]
@hit9 你整个五一都出去吗？大概空余的时间是什么时候？

**Comment by hit9** [comment]
@cliffwoo  :) 是的，29，30，1都出去吧～ 那个咱们 24，25的什么的可以么

**Comment by cliffwoo** [comment]
@hit9 可能会有豆瓣员工 和 中科院的某男从北京赶回来参加活动，所以就想定在假期了

**Comment by hit9** [comment]
@cliffwoo 额，好吧。

**Comment by cliffwoo** [comment]
@hit9 这次如果没机会，还有下次，以后还会不定期的搞的

**Comment by hit9** [comment]
@cliffwoo  ok ,

**Comment by jhsrcmh** [comment]
冒个泡，可惜这次参加不了了~O(∩_∩)O~

**Comment by guori12321** [comment]
等我下周考完GRE 一定要好好吃一顿～～希望这次分能够吧。。。

在 2013-04-20 22:08:26，"Minghui CHEN" notifications@github.com 写道：

冒个泡，可惜这次参加不了了~O(∩_∩)O~

**Comment by cliffwoo** [comment]
@jhsrcmh 也出去玩？

**Comment by jhsrcmh** [comment]
@cliffwoo  嗯:)
