### ISSUE TITLE
Hackathon的候选项目

### ISSUE THREAD

**Issue by cliffwoo** [HIT-ON-Github/About#8]
https://github.com/secreek/drinkup/issues?state=open

欢迎大家参与讨论!
即使因故无法参加的同学，也可以加入到讨论中 , 看看大家可以头脑风暴出什么好的idea。

**Comment by void-main** [comment]
https://github.com/secreek/drinkup/issues?labels=idea

这个可以直接看idea～～

**Comment by countcain** [comment]
两位大拿组织的真周到～～～～⊙ω⊙
在 2013-4-25 上午10:53，"Void Main" notifications@github.com写道：

**Comment by hit9** [comment]
吐血涛你去不去

**Comment by countcain** [comment]
看我提交的idea.....你呢？
在 2013-4-25 下午1:41，"Wang Chao" notifications@github.com写道：
